language:
- objective-c
env:
  global:
  - BUILD_COMMIT=latest-tag # comment out to build version in submodule
  - REPO_DIR=scipy
  matrix:
  # need numpy at least 1.6.2 to avoid '-faltivec' flag from np.distutils
  - VERSION=2.7.10 NUMPY_VERSION=1.6.2
  - VERSION=3.3.5 NUMPY_VERSION=1.7.1
  - VERSION=3.4.3 NUMPY_VERSION=1.7.1
install:
  # Install dual arch gfortran
  - sudo installer -pkg archives/gfortran-4.2.3.pkg -target /
  - source terryfy/travis_tools.sh
  - get_python_environment macpython $VERSION venv
  - pip install delocate
  - pip install cython
  - pip install numpy==$NUMPY_VERSION
  - if [ -n "$BUILD_COMMIT" ]; then
        checkout_commit $REPO_DIR $BUILD_COMMIT;
    fi
  - cd $REPO_DIR
  - export CC=clang
  - export CXX=clang++
  - python setup.py bdist_wheel
  - delocate-listdeps dist/*.whl # lists library dependencies
  - delocate-wheel dist/*.whl # copies library dependencies into wheel
  - delocate-addplat --rm-orig -x 10_9 -x 10_10 dist/*.whl
  - pip install dist/*.whl
  - cd ..
script:
  - pip install nose
  # Python 3.4 needs more recent numpy
  - if [ -n "$(pyver_ge $VERSION 3.4.0)" ]; then
    pip install --upgrade numpy;
    fi
  - mkdir tmp_test_dir
  - cd tmp_test_dir
  - python -c "import sys; import scipy; sys.exit(not scipy.test().wasSuccessful())"
  - arch -i386 python -c "import sys; import scipy; sys.exit(not scipy.test().wasSuccessful())"
  - cd ..
  - unset CC CXX # reset to default compilation for deploy modules
before_deploy: cd $REPO_DIR/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: "TSOBqCoQFnIjFb98ItonBT1ubfBo/pYsS7A69Q6lUAjl7Mun+F+XE4GgP0QxtiyFRBUsYZUQYsoqKoro3z/qKFUBfpBuFlPEPhtbRmoQAGSSKFtXBI9XxwJAiGL6CX/z22fCNOWWaWel4X6WacEb+ygoI+Hg21WFQT7djEFNctE="
  region: ORD
  container: wheels
  skip_cleanup: true
