language:
- objective-c
env:
  global:
  - SP_TAG=v0.14.0 # version of scipy to build
  - PACKAGES=scipy
  matrix:
  - VERSION=2.7.8
  - VERSION=3.3.5
  - VERSION=3.4.1 UPGRADE_NP=1 # fails against np 1.7.1
install:
  - cd numpy-atlas-binaries
  - git submodule update --init
  - cd scipy && git fetch --tags && cd ..
  - source travis_install.sh
script:
  - sudo rm -rf /usr/local/gfortran
  - mkdir tmp_test_dir
  - cd tmp_test_dir
  - source ../travis_test.sh
  - cd ../..
before_deploy: cd numpy-atlas-binaries/build/wheelhouse
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: "FoewqVjnW7ue8TYh+hqvgIW4ZWDumtsuVdLtx7VoHn9IZCmq7NrSYzigvPKZjZ35+KEO1qQEjUmRpzfTi1RIuqvqI8x9p9xlE18ndfyEOfJ8Yy2/EEYsE8kzhSZn1FWS4AmK2UYGthUVPdDX3koQO3niec27MbrQJCw9F5cIvg8="
  region: ORD
  container: wheels
  skip_cleanup: true
