language:
- objective-c
env:
  global:
  # - LATEST_TAG=1 # comment out to build version in submodule
  matrix:
  - VERSION=2.7.8 NUMPY_VERSION=1.5.1
  - VERSION=3.3.5 NUMPY_VERSION=1.7.1
  - VERSION=3.4.1 NUMPY_VERSION=1.7.1
install:
  - source terryfy/travis_tools.sh
  - get_python_environment macpython $VERSION venv
  - pip install delocate
  - pip install cython
  - pip install numpy==$NUMPY_VERSION
  - if [ -n "$LATEST_TAG" ]; then checkout_closest_tag scipy; fi
  - cd scipy
  - python setup.py bdist_wheel
  - delocate-listdeps dist/*.whl # lists library dependencies
  - delocate-wheel dist/*.whl # copies library dependencies into wheel
  - delocate-addplat --rm-orig -x 10_9 -x 10_10 dist/*.whl
  - pip install dist/*.whl
  - cd ..
script:
  - pip install nose
  - mkdir tmp_test_dir
  - cd tmp_test_dir
  - python -c "import sys; import scipy; sys.exit(not scipy.test().wasSuccessful())"
  - arch -i386 python -c "import sys; import scipy; sys.exit(not scipy.test().wasSuccessful())"
  - cd ..
before_deploy: cd scipy/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: "cihGM6hRwKIyd66zGCYLz4S1R1V/ubHEF5CZZ1oWKbO9ztDM/9Gjea2dnMMG7bCHoPMGj5ARMXwpwNnlpZyZgBTuJ/vV9CXKOyoCx+E6oixForAfK2QCikyBQaw7iUZYyM24FFlC4xw92I5sRi8kv6m0YiVCLfVWldmUXEj6nOo="
  region: ORD
  container: wheels
  skip_cleanup: true
