schedules:
- cron: "27 3 * * 0"
  # 3:27am UTC every Sunday
  displayName: Weekly build
  branches:
    include:
    - master
  always: true

pr:
- master

variables:
  BUILD_COMMIT: "master"

jobs:
  - template: azure-posix.yml
    parameters:
      name: linux
      vmImage: ubuntu-18.04
      matrix:
        amd64-linux-py3.10:
          AZURE_PYTHON_VERSION: "3.9"
          MB_PYTHON_VERSION: "3.10"
          MB_ML_VER: "2014"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
