schedules:
- cron: "27 3 * * 0"
  # 3:27am UTC every Sunday
  displayName: Weekly build
  branches:
    include:
    - master
  always: true

pr:
- master
- v1.9.x

variables:
  BUILD_COMMIT: "651a9b717"

jobs:
  - template: azure-posix.yml
    parameters:
      name: linux
      vmImage: ubuntu-18.04
      matrix:
        amd64-linux-py3.11:
          AZURE_PYTHON_VERSION: "3.9"
          MB_PYTHON_VERSION: "3.11"
          MB_ML_VER: "2014"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
  - template: azure-posix.yml
    parameters:
      name: macOS
      vmImage: macOS-10.15
      matrix:
        osx-Py311:
          AZURE_PYTHON_VERSION: "3.10"
          MB_PYTHON_VERSION: "3.11"
          MB_PYTHON_OSX_VER: "10.9"
          PLAT: x86_64
        osx-Py311-universal2:
          AZURE_PYTHON_VERSION: "3.10"
          MB_PYTHON_VERSION: "3.11"
          MB_PYTHON_OSX_VER: "10.9"
          PLAT: universal2
