schedules:
- cron: "27 3 * * 0"
  # 3:27am UTC every Sunday
  displayName: Weekly build
  branches:
    include:
    - master
  always: true

pr:
- master

variables:
  BUILD_COMMIT: "master"

jobs:
  - template: azure-posix.yml
    parameters:
      name: linux
      vmImage: ubuntu-18.04
      matrix:
        amd64-linux-py39:
          MB_PYTHON_VERSION: "3.9"
          NP_BUILD_DEP: "numpy==1.19.1"
          NP_TEST_DEP: "numpy==1.19.1"
        32bit-amd64-linux-py39:
          MB_PYTHON_VERSION: "3.9"
          NP_BUILD_DEP: "numpy==1.19.1"
          NP_TEST_DEP: "numpy==1.19.1"
          PLAT: "i686"
        amd64-linux-py38:
          MB_PYTHON_VERSION: "3.8"
          NP_BUILD_DEP: "numpy==1.17.3"
          NP_TEST_DEP: "numpy==1.17.3"
          CYTHON_BUILD_DEP: "Cython"
        32bit-amd64-linux-py38:
          MB_PYTHON_VERSION: "3.8"
          NP_BUILD_DEP: "numpy==1.17.3"
          NP_TEST_DEP: "numpy==1.17.3"
          CYTHON_BUILD_DEP: "Cython"
          PLAT: "i686"
        amd64-linux-py37:
          MB_PYTHON_VERSION: "3.7"
          NP_BUILD_DEP: "numpy==1.16.5"
          NP_TEST_DEP: "numpy==1.16.5"
          CYTHON_BUILD_DEP: "Cython"
        32bit-amd64-linux-py37:
          MB_PYTHON_VERSION: "3.7"
          NP_BUILD_DEP: "numpy==1.16.5"
          NP_TEST_DEP: "numpy==1.16.5"
          CYTHON_BUILD_DEP: "Cython"
          PLAT: "i686"

  - template: azure-posix.yml
    parameters:
      name: macOS
      vmImage: macOS-10.14
      matrix:
        osx-Py37:
          MB_PYTHON_VERSION: "3.7"
          NP_BUILD_DEP: "numpy==1.16.5"
          NP_TEST_DEP: "numpy==1.16.5"
          CYTHON_BUILD_DEP: "Cython"
        osx-Py38:
          MB_PYTHON_VERSION: "3.8"
          NP_BUILD_DEP: "numpy==1.17.3"
          NP_TEST_DEP: "numpy==1.17.3"
          CYTHON_BUILD_DEP: "Cython"
          MB_PYTHON_OSX_VER: "10.9"
        osx-Py39:
          MB_PYTHON_VERSION: "3.9"
          NP_BUILD_DEP: "numpy==1.19.1"
          NP_TEST_DEP: "numpy==1.19.1"
          CYTHON_BUILD_DEP: "Cython"
          MB_PYTHON_OSX_VER: "10.9"
