parameters:
  name: ""
  vmImage: ""
  matrix: []

jobs:
  - job: ${{ parameters.name }}
    timeoutInMinutes: 150
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      REPO_DIR: "scipy"
      PLAT: "x86_64"
      NIGHTLY_BUILD_COMMIT: "master"
      DAILY_COMMIT: "master"
    strategy:
      matrix:
        ${{ insert }}: ${{ parameters.matrix }}

    steps:
      - checkout: self
        submodules: true

      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(AZURE_PYTHON_VERSION)
        displayName: Set python version from AZURE
        condition: ne( coalesce (variables['AZURE_PYTHON_VERSION'], 'NONE'), 'NONE')

      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(MB_PYTHON_VERSION)
        displayName: Set python version from MB
        condition: eq( coalesce (variables['AZURE_PYTHON_VERSION'], 'NONE'), 'NONE')

      - bash: |
          set -e

          if [ "$BUILD_REASON" == "Schedule" ]; then
            BUILD_COMMIT=$NIGHTLY_BUILD_COMMIT
          fi
          echo "Building scipy@$BUILD_COMMIT"
          echo "##vso[task.setvariable variable=BUILD_COMMIT]$BUILD_COMMIT"

          # Platform variables used in multibuild scripts
          if [ `uname` == 'Darwin' ]; then
            echo "##vso[task.setvariable variable=TRAVIS_OS_NAME]osx"
            echo "##vso[task.setvariable variable=MACOSX_DEPLOYMENT_TARGET]10.9"
          else
            echo "##vso[task.setvariable variable=TRAVIS_OS_NAME]linux"
          fi

          # Store original Python path to be able to create test_venv pointing
          # to same Python version.
          PYTHON_EXE=`which python`
          echo "##vso[task.setvariable variable=PYTHON_EXE]$PYTHON_EXE"
        displayName: Define build env variables

      - bash: |
          set -ex
          echo building for commit "$BUILD_COMMIT"

          pip install --upgrade virtualenv wheel setuptools
          BUILD_DEPENDS="wheel oldest-supported-numpy Cython>=0.29.24 pybind11>=2.4.3 pythran"

          source multibuild/common_utils.sh
          source multibuild/travis_steps.sh

          before_install

          clean_code $REPO_DIR $BUILD_COMMIT
          ./patch_code.sh $REPO_DIR
          build_wheel $REPO_DIR $PLAT
        displayName: Build wheel

      - bash: |
          set -xe
          TEST_DEPENDS="oldest-supported-numpy pytest pytest-xdist pytest-faulthandler pytest-env"
          source multibuild/common_utils.sh
          source multibuild/travis_steps.sh
          install_run $PLAT
        displayName: Install wheel and test
        condition: ne(variables['PLAT'], 'arm64')


      - bash: |
          set -xe
          python verify_init.py ./wheelhouse
        displayName: "Check for appropriate contents of _distributor_init.py"

      - bash: |
          echo "##vso[task.prependpath]$CONDA/bin"
          sudo chown -R $USER $CONDA
        displayName: Add conda to PATH

      - bash: conda install -q -y anaconda-client
        displayName: Install anaconda-client

      - bash: |
          set -e
          if [ "$BUILD_COMMIT" == "master" ]; then
            ANACONDA_ORG="scipy-wheels-nightly"
            TOKEN="$MAPPED_SCIPY_WHEELS_NIGHTLY"
            echo getting SCIPY_WHEELS_NIGHTLY
          else
            ANACONDA_ORG="multibuild-wheels-staging"
            TOKEN="$MAPPED_SCIPY_STAGING_UPLOAD_TOKEN"
            echo getting SCIPY_STAGING_UPLOAD_TOKEN
          fi
          if [ "$TOKEN" == "" -o "${TOKEN:0:7}" == "\$(SCIPY" ]; then
            echo "##[warning] Could not find anaconda.org upload token in secret variables"
            TOKEN=""
          fi
          echo "##vso[task.setvariable variable=TOKEN]$TOKEN"
          echo "##vso[task.setvariable variable=ANACONDA_ORG]$ANACONDA_ORG"
        displayName: Retrieve secret upload token
        env:
          # Secret variables need to mapped to env variables explicitly:
          MAPPED_SCIPY_WHEELS_NIGHTLY: $(SCIPY_WHEELS_NIGHTLY)
          MAPPED_SCIPY_STAGING_UPLOAD_TOKEN: $(SCIPY_STAGING_UPLOAD_TOKEN)

      - bash: |
          set -e
          echo uploading wheelhouse/*.whl
          anaconda -v -t $TOKEN upload --force -u $ANACONDA_ORG wheelhouse/*.whl
          echo "PyPI-style index: https://pypi.anaconda.org/$ANACONDA_ORG/simple"
        displayName: Upload to anaconda.org (only if secret token is retrieved)
        condition: ne(variables['TOKEN'], '')
